package com.concussion.model;

public enum SymptomType {
    HEADACHE,
    PRESSURE_IN_HEAD,
    NECK_PAIN,
    NAUSEA,
    DIZZINESS,
    BLURRED_VISION,
    BALANCE_PROBLEMS,
    SENSITIVITY_TO_LIGHT,
    SENSITIVITY_TO_NOISE,
    FEELING_SLOWED_DOWN,
    FEELING_LIKE_IN_FOG,
    DONT_FEEL_RIGHT,
    DIFFICULTY_CONCENTRATING,
    DIFFICULTY_REMEMBERING,
    FATIGUE,
    CONFUSION,
    DROWSINESS,
    TROUBLE_FALLING_ASLEEP,
    MORE_EMOTIONAL,
    IRRITABILITY,
    SADNESS,
    NERVOUS_OR_ANXIOUS
}
